import React from 'react'
import Image1 from '../assets/images/Group1.svg';
import Image2 from '../assets/images/Group2.svg';
import Image3 from '../assets/images/Group3.svg';
import Image4 from '../assets/images/Group899.svg';
import Image5 from '../assets/images/Group900.svg';
import Image6 from '../assets/images/Group6.svg';
import Image7 from '../assets/images/Group7.svg';
import { popularNFtsPara } from '../assets/dummyData';

const PopularNFts = () => {
  return (
    <div id='Popular_NFTS' className='pt-5'>
    <div className='container'>
            <div className='row'>
                <div className='col-12'>
                    <h4 className='nft_heading'>Popular  NFT’s generated by Artists</h4>
                    <p className='nft_parah'>{popularNFtsPara}</p>
                </div>
            </div>
            <div className='row g-0'>
                <div className='col-12 d-flex gap-3 g-0'>
                    <div className='d-flex flex-column gap-3'>
                        <div className='img2'>
                            <img src={Image1} alt="Image" className='img-fluid w-100' />
                            <div className='d-flex justify-content-center align-items-center'>
                                <div className='red_box'>
                                </div>
                            </div>
                            <div className='text_img1'>
                                <h1>Bagwan</h1>
                                <p>Art by <span>xyz</span></p>
                            </div>

                        </div>
                        <div className='img1'>
                            <img src={Image2} alt="Image" className='img-fluid w-100 ' />
                            <div className='d-flex justify-content-center align-items-center'>
                                <div className='red_box'>

                                </div>
                            </div>
                            <div className='text_img1'>
                                <h1>Bagwan</h1>
                                <p>Art by <span>xyz</span></p>
                            </div>
                        </div>
                    </div>
                    <div className='d-flex flex-column gap-3'>
                        <div className='d-flex gap-3'>
                            <div className='img1'>
                                <img src={Image3} alt="Image" className='img-fluid w-100 ' />
                                <div className='d-flex justify-content-center align-items-center'>
                                    <div className='red_box'>
                                    </div>
                                </div>
                                <div className='text_img1'>
                                    <h1>Bagwan</h1>
                                    <p>Art by <span>xyz</span></p>
                                </div>
                            </div>
                            <div className='d-flex flex-column gap-3'>
                                <div className='img2'>
                                    <img src={Image4} alt="Image" className='img-fluid w-100'/>
                                    <div className='d-flex justify-content-center align-items-center red-box-outer'>
                                    <div className='red_box'>
                                    </div>
                                </div>
                                <div className='text_img1'>
                                    <h1>Bagwan</h1>
                                    <p>Art by <span>xyz</span></p>
                                </div>
                                    </div>
                                <div className='img2'> 
                                    <img src={Image5} alt="Image" className='img-fluid w-100 ' />
                                    <div className='d-flex justify-content-center align-items-center'>
                                    <div className='red_box'>
                                    </div>
                                </div>
                                <div className='text_img1'>
                                    <h1>Bagwan</h1>
                                    <p>Art by <span>xyz</span></p>
                                </div>
                                </div>
                            </div>
                        </div>
                        <div className='d-flex gap-3'>
                            <div className='img2'> 
                                <img src={Image6} alt="Image" className='img-fluid w-100 ' />
                                <div className='d-flex justify-content-center align-items-center'>
                                    <div className='red_box'>
                                    </div>
                                </div>
                                <div className='text_img1'>
                                    <h1>Bagwan</h1>
                                    <p>Art by <span>xyz</span></p>
                                </div>
                            </div>
                            <div className='img2'>
                                <img src={Image7} alt="Image" className='img-fluid w-100 ' />
                                <div className='d-flex justify-content-center align-items-center'>
                                    <div className='red_box'>
                                    </div>
                                </div>
                                <div className='text_img1'>
                                    <h1>Bagwan</h1>
                                    <p>Art by <span>xyz</span></p>
                                </div>
                                </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
        </div>
  )
}

export default PopularNFts
